/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sohak9660
 */
public class SecondScreen extends javax.swing.JFrame {

    /**
     * Creates new form SecondScreen
     */
    public SecondScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        LessonSelecter = new javax.swing.JLabel();
        ClassesofChamp = new javax.swing.JButton();
        StageofGame = new javax.swing.JButton();
        ChampionMatchups = new javax.swing.JButton();
        QuizLabel = new javax.swing.JLabel();
        Quiz = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 620));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 248, 75, 33);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 2, 36)); // NOI18N
        jLabel1.setText("Select Which Lesson you would like to learn");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(196, 48, 953, 37);

        jButton2.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton2.setText("Lesson 3");
        jPanel1.add(jButton2);
        jButton2.setBounds(991, 164, 140, 80);

        jButton3.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton3.setText("Lesson 1");
        jPanel1.add(jButton3);
        jButton3.setBounds(196, 164, 122, 80);

        jButton4.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton4.setText("Lesson 2");
        jPanel1.add(jButton4);
        jButton4.setBounds(588, 164, 140, 80);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tekton Pro", 2, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Classes\nOf \nChampions");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(196, 262, 122, 95);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tekton Pro", 2, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Stages\nOf\nGame");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(588, 262, 140, 95);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tekton Pro", 2, 24)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Classes\nOf \nChampions");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(991, 262, 140, 95);

        jButton5.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton5.setText("Quiz");
        jPanel1.add(jButton5);
        jButton5.setBounds(588, 449, 140, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1353, 0, 0, 0);

        LessonSelecter.setFont(new java.awt.Font("Tekton Pro", 0, 36)); // NOI18N
        LessonSelecter.setText("Please Select Which Lesson You Would Like To Learn");
        getContentPane().add(LessonSelecter);
        LessonSelecter.setBounds(309, 56, 734, 37);

        ClassesofChamp.setBackground(new java.awt.Color(255, 204, 204));
        ClassesofChamp.setText("Classes of Champions");
        ClassesofChamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassesofChampActionPerformed(evt);
            }
        });
        getContentPane().add(ClassesofChamp);
        ClassesofChamp.setBounds(309, 127, 150, 50);

        StageofGame.setBackground(new java.awt.Color(255, 204, 204));
        StageofGame.setText("Stages of Game");
        StageofGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StageofGameActionPerformed(evt);
            }
        });
        getContentPane().add(StageofGame);
        StageofGame.setBounds(614, 127, 140, 50);

        ChampionMatchups.setBackground(new java.awt.Color(255, 204, 204));
        ChampionMatchups.setText("Champion Matchups");
        ChampionMatchups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChampionMatchupsActionPerformed(evt);
            }
        });
        getContentPane().add(ChampionMatchups);
        ChampionMatchups.setBounds(893, 127, 150, 50);

        QuizLabel.setFont(new java.awt.Font("Tekton Pro", 0, 36)); // NOI18N
        QuizLabel.setText("Are You Ready For The Quiz?");
        getContentPane().add(QuizLabel);
        QuizLabel.setBounds(471, 243, 405, 37);

        Quiz.setText("Yes");
        Quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizActionPerformed(evt);
            }
        });
        getContentPane().add(Quiz);
        Quiz.setBounds(616, 317, 140, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Demacia123.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -20, 1360, 620);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new NewJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClassesofChampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassesofChampActionPerformed
        // TODO add your handling code here:
         new ClassesofChampions().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ClassesofChampActionPerformed

    private void StageofGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StageofGameActionPerformed
        // TODO add your handling code here:
        new StagesOfGame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_StageofGameActionPerformed

    private void ChampionMatchupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChampionMatchupsActionPerformed
        // TODO add your handling code here:
        new ChampionMatchups().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ChampionMatchupsActionPerformed

    private void QuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizActionPerformed
new Quiz().setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_QuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChampionMatchups;
    private javax.swing.JButton ClassesofChamp;
    private javax.swing.JLabel LessonSelecter;
    private javax.swing.JButton Quiz;
    private javax.swing.JLabel QuizLabel;
    private javax.swing.JButton StageofGame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
