/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sohak9660
 */
public class StagesOfGame extends javax.swing.JFrame {

    /**
     * Creates new form StagesOfGame
     */
    public StagesOfGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MidGame = new javax.swing.JTextField();
        EarlyGameInfo = new javax.swing.JTextField();
        LateGame = new javax.swing.JTextField();
        EarlyGameInfo1 = new javax.swing.JLabel();
        EarlyGameInfo3 = new javax.swing.JLabel();
        EarlyGameInfo4 = new javax.swing.JLabel();
        EarlyGameInfo2 = new javax.swing.JLabel();
        MidGameInfo1 = new javax.swing.JLabel();
        MidGameInfo2 = new javax.swing.JLabel();
        MidGameInfo3 = new javax.swing.JLabel();
        MidGameInfo4 = new javax.swing.JLabel();
        LateGameInfo1 = new javax.swing.JLabel();
        LateGameInfo2 = new javax.swing.JLabel();
        LateGameInfo3 = new javax.swing.JLabel();
        LateGameInfo4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1700, 1700));
        getContentPane().setLayout(null);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(0, 672, 55, 23);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1127, 109, 0, 0);

        MidGame.setFont(new java.awt.Font("Tekton Pro", 2, 36)); // NOI18N
        MidGame.setText("  Mid Game");
        MidGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MidGameActionPerformed(evt);
            }
        });
        getContentPane().add(MidGame);
        MidGame.setBounds(650, 70, 164, 107);

        EarlyGameInfo.setFont(new java.awt.Font("Tekton Pro", 2, 36)); // NOI18N
        EarlyGameInfo.setText("  Early Game");
        EarlyGameInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarlyGameInfoActionPerformed(evt);
            }
        });
        getContentPane().add(EarlyGameInfo);
        EarlyGameInfo.setBounds(120, 60, 196, 107);

        LateGame.setFont(new java.awt.Font("Tekton Pro", 2, 36)); // NOI18N
        LateGame.setText("Late Game");
        LateGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LateGameActionPerformed(evt);
            }
        });
        getContentPane().add(LateGame);
        LateGame.setBounds(1080, 60, 164, 107);

        EarlyGameInfo1.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EarlyGameInfo1.setText("Get gold by killing minions");
        getContentPane().add(EarlyGameInfo1);
        EarlyGameInfo1.setBounds(120, 180, 196, 41);

        EarlyGameInfo3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EarlyGameInfo3.setText("Use Wards to Light up map");
        getContentPane().add(EarlyGameInfo3);
        EarlyGameInfo3.setBounds(120, 270, 196, 41);

        EarlyGameInfo4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EarlyGameInfo4.setText("Figure out enemies position");
        getContentPane().add(EarlyGameInfo4);
        EarlyGameInfo4.setBounds(120, 310, 196, 41);

        EarlyGameInfo2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EarlyGameInfo2.setText("Get into fights with # adv");
        getContentPane().add(EarlyGameInfo2);
        EarlyGameInfo2.setBounds(120, 220, 196, 41);

        MidGameInfo1.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        MidGameInfo1.setText("Destroy Turrets");
        getContentPane().add(MidGameInfo1);
        MidGameInfo1.setBounds(650, 190, 196, 41);

        MidGameInfo2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        MidGameInfo2.setText("Kill Dragons/Baron");
        getContentPane().add(MidGameInfo2);
        MidGameInfo2.setBounds(650, 230, 196, 41);

        MidGameInfo3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        MidGameInfo3.setText("Push Minion Lanes");
        getContentPane().add(MidGameInfo3);
        MidGameInfo3.setBounds(650, 270, 196, 41);

        MidGameInfo4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        MidGameInfo4.setText("Keep map warded");
        getContentPane().add(MidGameInfo4);
        MidGameInfo4.setBounds(650, 320, 196, 41);

        LateGameInfo1.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        LateGameInfo1.setText("Break into Enemy Core");
        getContentPane().add(LateGameInfo1);
        LateGameInfo1.setBounds(1080, 170, 196, 41);

        LateGameInfo2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        LateGameInfo2.setText("Destroy Enemy Nexus");
        getContentPane().add(LateGameInfo2);
        LateGameInfo2.setBounds(1080, 210, 196, 41);

        LateGameInfo3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        LateGameInfo3.setText("Kill Elder Dragon");
        getContentPane().add(LateGameInfo3);
        LateGameInfo3.setBounds(1080, 250, 196, 41);

        LateGameInfo4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        LateGameInfo4.setText("Try and Flank Enemy");
        getContentPane().add(LateGameInfo4);
        LateGameInfo4.setBounds(1080, 290, 196, 41);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LL.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 1370, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
          new SecondScreen().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void MidGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MidGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MidGameActionPerformed

    private void EarlyGameInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EarlyGameInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EarlyGameInfoActionPerformed

    private void LateGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LateGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LateGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StagesOfGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StagesOfGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StagesOfGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StagesOfGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StagesOfGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField EarlyGameInfo;
    private javax.swing.JLabel EarlyGameInfo1;
    private javax.swing.JLabel EarlyGameInfo2;
    private javax.swing.JLabel EarlyGameInfo3;
    private javax.swing.JLabel EarlyGameInfo4;
    private javax.swing.JTextField LateGame;
    private javax.swing.JLabel LateGameInfo1;
    private javax.swing.JLabel LateGameInfo2;
    private javax.swing.JLabel LateGameInfo3;
    private javax.swing.JLabel LateGameInfo4;
    private javax.swing.JTextField MidGame;
    private javax.swing.JLabel MidGameInfo1;
    private javax.swing.JLabel MidGameInfo2;
    private javax.swing.JLabel MidGameInfo3;
    private javax.swing.JLabel MidGameInfo4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    // End of variables declaration//GEN-END:variables
}
